"""
Task: Project Euler #2: Even Fibonacci numbers
URL: https://www.hackerrank.com/contests/projecteuler/challenges/euler002
Description: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1,2,3,5,8,13,21,34,55,89,...
By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.
"""

T = int(raw_input().strip())
Ns = []
for i in xrange(T):
    Ns.append(int(raw_input().strip()))

for N in Ns:

    total = 0

    el = 2
    el_prev = 1
    
    while el < N:

        if el % 2 == 0:
            total += el

        el_tmp = el_prev
        el_prev = el
        el += el_tmp

    print total